sortStrings
js-tasks-ru/js-20201211_burda3000 pull request #2
Opened 2020-12-16 21:09 UTC by alex-shostka

Тесты проходят. Дублирование кода при решении. Не знаю, как зарефакторить. Подумаю еще, может придет мысль.

2020-12-16 23:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```

2020-12-17 08:20 UTC, alex-shostka commented
А, понятно. Я думал, что можно сдавать по одной задаче.  т.е. сделал задачу, отправил PR и пока ожидаешь ответа, добавляешь и делаешь другую задачу. Это тесты из другой задачи. Хорошо, как решу задачи - отправлю.

2020-12-17 23:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      a.localeCompare(b, ["ru", "en"], { caseFirst: "upper" })
cтрока 11 дублирует строку 16 исключением порядка аргументов в методе `localeCompare` - от дублирования нужно избавиться

2020-12-17 23:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let array = arr.slice();
проверьте точно ди `let`? может `const`?

2020-12-17 23:09 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-12-17 23:36 UTC, alex-shostka commented on 02-javascript-data-types/1-sort-strings/index.js
> +      a.localeCompare(b, ["ru", "en"], { caseFirst: "upper" })
Да,  я понимаю, что нужно избавиться. Но я пока не понимаю, как это сделать.

2020-12-18 09:51 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-18 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 14:54 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      a.localeCompare(b, ["ru", "en"], { caseFirst: "upper" })
@alex-shostka хорошо, мы это обсудим на занятии. Пока оставим так

2020-12-18 14:54 UTC, dosandk approved these changes

2020-12-18 14:55 UTC, merged