homework 5 and 6
js-tasks-ru/js-20201211_burda3000 pull request #6
Opened 2021-01-04 19:56 UTC by alex-shostka

2021-01-04 20:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
- should be rendered correctly
- should have ability to set slider boundaries
- should have ability to set selected range
- should have ability to move left slider to start boundary
- should have ability to move right slider to end boundary
- should have ability to select all range
- should have ability to select single value (when min and max range equal)
- should have ability to set range value, for example: usd, eur, etc.
- should produce event "range-select"
- should have a new ranges in produced event
- should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2021-01-04 21:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
- should be rendered correctly
- should have ability to set slider boundaries
- should have ability to set selected range
- should have ability to move left slider to start boundary
- should have ability to move right slider to end boundary
- should have ability to select all range
- should have ability to select single value (when min and max range equal)
- should have ability to set range value, for example: usd, eur, etc.
- should produce event "range-select"
- should have a new ranges in produced event
- should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2021-01-04 21:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
- should be rendered correctly
- should have ability to set slider boundaries
- should have ability to set selected range
- should have ability to move left slider to start boundary
- should have ability to move right slider to end boundary
- should have ability to select all range
- should have ability to select single value (when min and max range equal)
- should have ability to set range value, for example: usd, eur, etc.
- should produce event "range-select"
- should have a new ranges in produced event
- should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2021-01-06 19:10 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to select single value (when min and max range equal)
+ should have ability to set range value, for example: usd, eur, etc.
+ should produce event "range-select"
+ should have a new ranges in produced event
+ should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-07 13:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.element.remove();
здесь нужно снять обработчики событий с `document`

2021-01-07 13:40 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener("pointerover", (e) => {
при использовании анонимных стрелочных функций, снять обработчики событий не получится. Используйте стрелочные функции как class properties

2021-01-07 13:40 UTC, dosandk requested changes
решение `Tooltip` необходимо поправить. Смотрите коммент

2021-01-08 04:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-10 18:15 UTC, dosandk approved these changes
good 👍

2021-01-10 18:16 UTC, merged